### PR TITLE
Show: Support Directory and can monitor dir's files increase.

### PR DESCRIPTION
**Pull request by YongHaoWu**

### CODE REVIEW

**Comment by YongHaoWu** [comment]
@mengxy  plz have a check

**Comment by YongHaoWu** [comment]
@dongmx

**Comment by YongHaoWu** [comment]
thanks @dongmx

**Comment by dongmx** [comment]
@YongHaoWu You are very welcome :)

**Comment by YongHaoWu** [comment]
@dongmx  I am curious. Do u really review my code? haha

**Comment by dongmx** [comment]
@YongHaoWu Reviewed, but no tests.

**Pull request merged**
